[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "torch_dev_utils"
version = "0.1.0"
requires-python=">=3.11"
dependencies = [
    "tensorboard>=2.20.0",
    "tqdm>=4.66.5",
    "tgt>=1.4.4",
    "gruut>=2.4.0",
    "nltk>=3.9.2",
    "transformers[sentencepiece]>=4.56.2",
    "torch>=2.8.0",
    "fastdtw>=0.3.4"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
    "mypy>=1.18.1",
    "pre-commit>=4.3.0",
    "autopep8>=2.3.2",
    "pylint>=3.1.0",
]

[tool.coverage.report]
fail_under = 90
