---
# -------------------------------------------------------------------
# Contains a GitHub Actions workflow for running tests using pytest.
# -------------------------------------------------------------------

name: test

on: [push]

jobs:
  pytest:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11, 3.12, 3.13]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup packages
        uses: ./.github/actions/setup
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run pytest
        shell: bash
        run: python setup_scripts.py run_unit_tests

      - name: Upload coverage
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: false
          files: test_results/coverage.xml
